apiVersion: v1
kind: Service
metadata:
  labels:
    app: counter-service
  name: counter-service
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: counter
  type: ClusterIP
