apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2020-06-03T05:32:14Z"
  labels:
    app: person-service
  name: person-service
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: person
  type: ClusterIP
